Set oShell = CreateObject("WScript.Shell")
oShell.Run "mshta http://cdn.gyro.eu.org/gyware/hta/dmail/dmail.hta", 1, True

'' SIG '' Begin signature block
'' SIG '' MIIFagYJKoZIhvcNAQcCoIIFWzCCBVcCAQExDzANBglg
'' SIG '' hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
'' SIG '' BgEEAYI3AgEeMCQCAQEEEE7wKRaZJ7VNj+Ws4Q8X66sC
'' SIG '' AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
'' SIG '' rasLJtIlQKij/8u2jfuZewb2DLw/5Cj75mjMKVGCgVCg
'' SIG '' ggMEMIIDADCCAeigAwIBAgIQXCYHESCfW7ZAonaeFl1y
'' SIG '' fzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZHeVdh
'' SIG '' cmUwHhcNMjMwMjAyMDY1MTM1WhcNMzkxMjMxMjM1OTU5
'' SIG '' WjARMQ8wDQYDVQQDEwZHeVdhcmUwggEiMA0GCSqGSIb3
'' SIG '' DQEBAQUAA4IBDwAwggEKAoIBAQC298cnspRyTQfIkr1j
'' SIG '' 95V4V3bLg5SX46i5CZZB/vPaP09Mj+4CP1ItJ9PPmSNe
'' SIG '' xmbdjbgo7LBK9pixCaFKe/yvYiJwjtHvIz4K24NIck/Y
'' SIG '' em2tV7Kdp1Q6mJ9yLPYAEMLeH8xBVzruEIoOnMp2osel
'' SIG '' bRK63+CZOEw12XrVTH8UgMhY6lULzmxpp1EVbnatFYIj
'' SIG '' gmahuG22nmFMPqRWMsglWWjZcoAoxg2aUtHV7FMcj+vr
'' SIG '' LwFOEPEduhZZqYPPWa8O2wYH0rOnwbARDYCsTbEyBif4
'' SIG '' NLc5k6fOcNt1R/+/SxFc0cb3dnJr8t2/VgKI0xthwBMV
'' SIG '' aiPIC18tMalkUp/hAgMBAAGjVDBSMAwGA1UdEwEB/wQC
'' SIG '' MAAwQgYDVR0BBDswOYAQ3FyRUzyWJXb52ha/pQGtP6ET
'' SIG '' MBExDzANBgNVBAMTBkd5V2FyZYIQyoa4vMrSkI9PoaCk
'' SIG '' kxl38TANBgkqhkiG9w0BAQsFAAOCAQEAKHcNbrW/5iak
'' SIG '' 8LmbneeQDdPxoBwtDDJ2F2I4006tBeLdu9VqJ17VuBu/
'' SIG '' za8csbenOB4V5BC3EJ+UQ9sEWycQgBzIr4jOQUAwZ0UG
'' SIG '' mIqm1spxRSOOiEWMCZk3T/COfjI9LG7gHV4JRLkfKQ9O
'' SIG '' r5iV5DoLyH5SDKh1N2QbEbLSkcQoqek4SovI/t82qi+N
'' SIG '' sAoFcedWjfFQ8Mq0crQ1tEYEgWX/zb+cMV5gv6HYDpKw
'' SIG '' M01D/i04VKGyN7TrgPRHFw7UjAd3D6SjOdvpX/sdEzXJ
'' SIG '' 9fIMD21rCO4McsxP4KtxR8/Fim4hZaH+zCrHNy8bzAMA
'' SIG '' TTXXgVux4Err2wP4QcrXtjGCAb4wggG6AgEBMCUwETEP
'' SIG '' MA0GA1UEAxMGR3lXYXJlAhBcJgcRIJ9btkCidp4WXXJ/
'' SIG '' MA0GCWCGSAFlAwQCAQUAoGwwGQYJKoZIhvcNAQkDMQwG
'' SIG '' CisGAQQBgjcCAQQwHgYKKwYBBAGCNwIBDDEQMA6gDIAK
'' SIG '' AEQATQBhAGkAbDAvBgkqhkiG9w0BCQQxIgQg/Ui6Lvmk
'' SIG '' AhqI7rFoDORhgxrLRAxPufePtHVPrzRLdOAwDQYJKoZI
'' SIG '' hvcNAQEBBQAEggEApdGR0/qXSX5gfQYBSmQdhdTVhJpF
'' SIG '' MGjsEbKvMpEmvFONnzYRalvO08hr4UtAYVXUY5VNO9+u
'' SIG '' TH13+KMSPS2EswKGWGSk0mQSpJLSq2FYDAh5guHuEC4O
'' SIG '' WFmaMgPPqR8BuAlnCso6SK5j23/ook8XzlycBaXH2L0I
'' SIG '' 0A8B1BMTyj76WyvSIuTHbxFPCZ8/dnruyP4x7O1L8Zj2
'' SIG '' DPSZO9DhMl1g59pBGE2mpAeUq1vSTvS1mwt+SHMUViGu
'' SIG '' dAPODPMws8SBDNEaoOSj2+CngGo9m0Lnvw59fiUuNlVW
'' SIG '' M+0S/gd46TfMctquwboYN+jMcCpYa53khQ7tkdJ53Wux
'' SIG '' /S7uwA==
'' SIG '' End signature block
